from models.hcha import HCHA
from models.hnhn import HNHN
from models.hypergcn import HyperGCN
from models.hypersage import HyperSAGE
from models.legcn import LEGCN
from models.unigcn2 import UniGCNII
from models.hypernd import HyperND
from models.allset import SetGNN
from models.edgnn import EquivSetGNN
from models.directedhypergraph import Future_node_classification
#from models.directedhypergraph_gcn import Future_node_classification_new
from models.phenonmnn import GCNModel